apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mario-service-loadbalancer-backend-config
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 3
    healthyThreshold: 2
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /
    port: 8080
